version: '3.8'

services:

  discovery-service:
    image: lab7-eurekaserver:latest
    build:
      context: "./Discovery_Service"
    ports:
      - "8761:8761"
    environment:
      - SPRING_APPLICATION_NAME=discovery-service
      - SERVER_PORT=8761
    networks:
      - app-network

  genres-microservice:
    build:
      context: "./Library_Genres"
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_genres:5432/genresdb
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_APPLICATION_NAME=genres-microservice
      - SERVER_PORT=8081

      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - app-network
    depends_on:
      - postgres_genres
      - discovery-service

  books-microservice-1:
    build:
      context: "./Library_Books"
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_books:5432/booksdb
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_APPLICATION_NAME=books-microservice
      - SERVER_PORT=8082

      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - app-network
    depends_on:
      - postgres_books
      - discovery-service

  books-microservice-2:
    build:
      context: "./Library_Books"
    ports:
      - "8083:8083"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_books:5432/booksdb
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_APPLICATION_NAME=books-microservice
      - SERVER_PORT=8083

      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - app-network
    depends_on:
      - postgres_books
      - discovery-service

  gateway:
    build:
      context: "./Library_Gateway"
    ports:
      - "8080:8080"
    environment:
      - SPRING_APPLICATION_NAME=gateway-service
      - SERVER_PORT=8080
      - SPRING_MAIN_WEB_APPLICATION_TYPE=reactive

      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - app-network
    depends_on:
      - discovery-service

  angular-app:
    build:
      context: "./library-angular-app"
    container_name: angular-app
    ports:
      - "4200:80"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    networks:
      - app-network

  postgres_genres:
    image: postgres:15.2
    environment:
      POSTGRES_DB: genresdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    networks:
      - app-network

  postgres_books:
    image: postgres:15.2
    environment:
      POSTGRES_DB: booksdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge